### ISSUE TITLE
Unsupported OS Debian isn't correctly catch 

### ISSUE THREAD

**Issue by hdep** [NTTCom-MS/eyp-postfix#58]
Hello,

I tried you module on Debian and it failed : 

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Unsupported (file: /etc/puppetlabs/code/environments/qualification/modules/postfix/manifests/params.pp, line: 131, column: 21) on node client.domain.local
`

On line 131 I got :  

        'Debian': { fail('Unsupported')  }

**Comment by jordiprats** [comment]
Hi,
I haven't tested this module on Debian so that's the reason I'm setting it as unsupported. I believe thou it's going to be pretty straightforward to implement Debian support since I have tested it under Ubuntu.

If you submit a PR with any change that needs to be done I'll be more than happy to merge it

best regards,

**Comment by hdep** [comment]
Thank you for your feedback.
I found another module similar so I don't think I'll have the time for this.
But thanks !
